#!/usr/bin/env bash

PROFILE_NAME="wsl"
PROFILE_DESC="WSL2 development environment"

PROFILE_MODULES=(core shell cli-tools ssh neovim tmux node secrets)
PROFILE_DOTFILES=(common)

OPTIONAL_MODULES=(php dotnet)
