#!/usr/bin/env bash

dry_run="0"

if [[ -z $XDG_CONFIG_HOME ]]; then
  echo "XDG_CONFIG_HOME not defined"
  echo "Using ~/.config"
  XDG_CONFIG_HOME=$HOME/.config
fi

if [[ -z $DEV_ENV ]]; then
  echo "DEV_ENV needs to be set"
  exit 1
fi

log() {
  if [[ $dry_run == "1" ]]; then
    echo "[DRY_RUN]: $1"
  else
    echo "$1"
  fi
}

log "env: $DEV_ENV"

update_files() {
  log "Copying over files from: $1"
  pushd $1 &>/dev/null
  (
    configs=$(find . -mindepth 1 -maxdepth 1 -type d)
    for c in $configs; do
      directory=${2%/}/${c#./}
      log "    Removing: rm -rf $directory"

      if [[ $dry_run == "0" ]]; then
        rm -rf $directory
      fi

      log "    Copying env: cp -r $c $2"
      if [[ $dry_run == "0" ]]; then
        cp -r ./$c $2
      fi
    done

  )
  popd &>/dev/null
}

copy() {
  log "Removing: $2"
  if [[ $dry_run == "0" ]]; then
    rm $2
  fi
  log "Copying: $1 to $2"
  if [[ $dry_run == "0" ]]; then
    cp $1 $2
  fi
}

update_files $DEV_ENV/env/.config $XDG_CONFIG_HOME
update_files $DEV_ENV/env/.local $HOME/.local

copy $DEV_ENV/env/.aliases $HOME/.aliases
copy $DEV_ENV/env/.zshenv $HOME/.zshenv
copy $DEV_ENV/env/.zshrc $HOME/.zshrc
copy $DEV_ENV/env/.gitconfig $HOME/.gitconfig
copy $DEV_ENV/env/.config/starship.toml $XDG_CONFIG_HOME
