#!/usr/bin/env bash

set -euo pipefail

source ./utils/os-detect.sh

os=$(detect_os)

case "$os" in
arch)
  paru -S --noconfirm --needed bat bc curl eza fzf fd jq lazygit mise openssh ripgrep tldr vim unzip wget wl-clipboard zoxide
  ;;
ubuntu)
  sudo apt-get update
  sudo apt-get install -y bat bc curl exa fzf fd-find gpg jq lazygit openssh-client ripgrep tldr vim unzip wget wl-clipboard zoxide
  ln -s $(which fdfind) ~/.local/bin/fd

  sudo install -dm 755 /etc/apt/keyrings
  wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | sudo tee /etc/apt/keyrings/mise-archive-keyring.gpg 1> /dev/null
  echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/mise.list
  sudo apt update
  sudo apt install -y mise
  ;;
esac
