#!/usr/bin/env bash

set -euo pipefail

# Source OS detection script
source ./utils/os-detect.sh

os=$(detect_os)

case "$os" in
arch)
  sudo pacman -S mise
  ;;
ubuntu)
  ;;
esac

sudo pacman -S mise
mise use -g node@24
npm -g i neovim
