#!/usr/bin/env bash

/bin/bash -c "$(curl -fsSL https://php.new/install/linux/8.4)"

item_id="421bb870-b923-44e6-b2fe-b38c0009bfe3"
bw get item "$item_id" | jq -r '.fields[] | select(.name=="Licence Key") | .value' > "$HOME/intelephense/licence.txt"
