#!/usr/bin/env bash

set -euo pipefail

if ! command -v mise >/dev/null 2>&1; then
    echo "mise is not installed or not in PATH."
    exit 1
fi

mise use -g dotnet@9

pushd "$HOME"
dotnet new tool-manifest
dotnet tool install -g csharpier
popd
