#!/usr/bin/env bash

if [[ -n "$WSL_DISTRO_NAME" ]] || grep -qi microsoft /proc/version; then
    exit 0
fi

paru -S --noconfirm --needed ttf-font-awesome waybar ttf-jetbrains-mono-nerd ttf-nerd-fonts-symbols
paru -S --noconfirm --needed hyprlock
paru -S --noconfirm --needed hyprpaper hypridle
paru -S --noconfirm --needed wlogout-git
paru -S --noconfirm --needed qt5ct qt5-wayland qt5-quickcontrols2 qt6ct qt6-wayland networkmanager catppuccin-cursors-mocha
paru -S --noconfirm --needed zen-browser-bin thunar

