#!/usr/bin/env bash

set -euo pipefail

# Install dependencies
sudo pacman -S --needed --noconfirm base-devel git

# Remove existing paru
if command -v paru >/dev/null 2>&1; then
    paru -R --noconfirm paru
fi

# Remove existing paru directory
paru_dir="$HOME/paru"
[[ -d "$paru_dir" ]] && rm -rf "$paru_dir"

# Install paru
git clone https://aur.archlinux.org/paru.git "$paru_dir"
pushd "$paru_dir"
makepkg -si
popd

paru -S --noconfirm --needed ansible-core
