#!/usr/bin/env bash
# Configuration loading and parsing

# ============================================================================
# Safe Source Helper
# ============================================================================

# Safely source a config file with path validation
# Usage: safe_source "$file" "description"
safe_source() {
    local file="$1"
    local desc="${2:-config}"
    
    # Must exist and be readable
    if [[ ! -f "$file" ]]; then
        error_exit "$desc not found: $file"
    fi
    if [[ ! -r "$file" ]]; then
        error_exit "$desc not readable: $file"
    fi
    
    # No path traversal
    if [[ "$file" == *".."* ]]; then
        error_exit "$desc contains invalid path: $file"
    fi
    
    # Must be within allowed locations
    local real_path
    real_path="$(realpath "$file" 2>/dev/null)" || real_path="$file"
    if [[ "$real_path" != "$DEV_ROOT"/* && "$real_path" != "$HOME"/* ]]; then
        error_exit "$desc outside allowed locations: $file"
    fi
    
    source "$file"
}

# ============================================================================
# Machine Configuration
# ============================================================================

load_machine_config() {
    local machine_conf="$DEV_ROOT/.local/machine.conf"
    
    if [[ -f "$machine_conf" ]]; then
        safe_source "$machine_conf" "Machine config"
        return 0
    fi
    return 1
}

save_machine_config() {
    local profile="$1"
    local machine_name="$2"
    
    mkdir -p "$DEV_ROOT/.local"
    
    cat > "$DEV_ROOT/.local/machine.conf" <<EOF
# Machine configuration - generated by ./dev init
# Edit this file to customize your setup

PROFILE="$profile"
MACHINE_NAME="$machine_name"

# Add extra modules beyond profile defaults
# Example: EXTRA_MODULES=(php dotnet)
EXTRA_MODULES=()

# Skip specific modules from profile
# Example: SKIP_MODULES=(desktop)
SKIP_MODULES=()

# Include Windows desktop configs (yasb, glazewm, etc.)
# Useful for WSL users who want to manage Windows-side tools
INCLUDE_WINDOWS=false

# Include work dotfiles layer (requires dotfiles/work submodule)
INCLUDE_WORK=false
EOF
}

# ============================================================================
# Profile Configuration
# ============================================================================

load_profile() {
    local profile="$1"
    local profile_conf="$DEV_ROOT/config/profiles/${profile}.conf"
    
    if [[ ! -f "$profile_conf" ]]; then
        error_exit "Profile not found: $profile"
    fi
    
    safe_source "$profile_conf" "Profile config"
}

# ============================================================================
# Package Configuration
# ============================================================================

load_packages() {
    local packages_conf="$DEV_ROOT/config/packages.conf"
    
    if [[ ! -f "$packages_conf" ]]; then
        error_exit "Packages config not found: $packages_conf"
    fi
    
    safe_source "$packages_conf" "Packages config"
}
