#!/usr/bin/env bash
# Configuration loading and parsing

# ============================================================================
# Machine Configuration
# ============================================================================

load_machine_config() {
    local machine_conf="$DEV_ROOT/.local/machine.conf"
    
    if [[ -f "$machine_conf" ]]; then
        source "$machine_conf"
        return 0
    fi
    return 1
}

save_machine_config() {
    local profile="$1"
    local machine_name="$2"
    
    mkdir -p "$DEV_ROOT/.local"
    
    cat > "$DEV_ROOT/.local/machine.conf" <<EOF
# Machine configuration - generated by ./dev init
# Edit this file to customize your setup

PROFILE="$profile"
MACHINE_NAME="$machine_name"

# Add extra modules beyond profile defaults
# Example: EXTRA_MODULES=(php dotnet)
EXTRA_MODULES=()

# Skip specific modules from profile
# Example: SKIP_MODULES=(desktop)
SKIP_MODULES=()

# Include work dotfiles layer (requires dotfiles/work submodule)
INCLUDE_WORK=false
EOF
}

# ============================================================================
# Profile Configuration
# ============================================================================

load_profile() {
    local profile="$1"
    local profile_conf="$DEV_ROOT/config/profiles/${profile}.conf"
    
    if [[ ! -f "$profile_conf" ]]; then
        error_exit "Profile not found: $profile"
    fi
    
    source "$profile_conf"
}

# ============================================================================
# Package Configuration
# ============================================================================

load_packages() {
    local packages_conf="$DEV_ROOT/config/packages.conf"
    
    if [[ ! -f "$packages_conf" ]]; then
        error_exit "Packages config not found: $packages_conf"
    fi
    
    source "$packages_conf"
}
