#!/usr/bin/env bash

core_common=(git)
core_arch=(base-devel)
core_ubuntu=(build-essential)

cli_common=(bat curl wget jq bc unzip fzf ripgrep lazygit tldr zoxide wl-clipboard vim)
cli_arch=(eza fd mise openssh)
cli_ubuntu=(fd-find gpg openssh-client)

desktop_arch=(cmake meson cpio)

shell_common=(zsh)
shell_arch=(starship)

neovim_arch=(neovim)

tmux_common=(tmux)

secrets_arch=(bitwarden-cli)
