# Gazelle WiFi TUI - floating window like Impala
# Using windowrulev2 and initialClass for xdg-terminal-exec compatibility
windowrule {
  name = windowrule-1
  float = on
  center = on
  size = 800 600
  match:initial_class = (Gazelle)
}


windowrule {
  name = windowrule-2
  fullscreen = on
  allows_input = on
  border_size = 0
  no_blur = on
  no_anim = on
  no_dim = on
  no_shadow = on
  match:title = (Guild Wars 2)
}

